spring.application.name=springboot
smartpulse.ml.service.url=http://127.0.0.1:8000
spring.datasource.url=jdbc:mysql://localhost:3307/smartpulse_db
spring.datasource.username=root
spring.datasource.password=${SMARTPULSE_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver